name: flutter_test_chat1
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  
  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.3
  dartz: ^0.10.1
  equatable: ^2.0.0
  get_it: ^7.6.4
  device_preview: ^1.1.0
  internet_connection_checker: ^1.0.0+1
  http: ^1.1.0
  shared_preferences: ^2.2.1
  image_picker: ^1.0.3
  bloc: ^8.1.2
  flutter_svg: ^2.0.9
  dropdown_button2: ^2.3.8
  flutter_screenutil: ^5.9.0
  firebase_messaging: ^14.7.10
  firebase_core: ^2.24.2
  rename: ^3.0.1
  mockito: ^5.4.4
  build_runner: ^2.4.8

dev_dependencies:
  flutter_launcher_icons: "^0.13.1"
  
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/Png/download.png"  
  flutter_test:
    sdk: flutter

  
  flutter_lints: ^2.0.0




flutter:


  uses-material-design: true

  
  assets:
    - assets/images/Png/
    - assets/images/Svg/

  
  
  fonts:
    - family: PoppinsSemiBold
      fonts:
        - asset: assets/fonts/Poppins-SemiBold.ttf

    - family:  PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
        
    - family:  PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
  
  